### PR TITLE
Add new feature: enumerable methods

### PR DESCRIPTION
**Pull request by carlos-osorio-developer**
Ruby Enumerable Methods

This project implements existing ruby enumerable methods, but all of them were made with our own knowledge of the ruby language, the methods created were:

- my_each
- my_each_with_index
- my_select
- my_all
- my_any
- my_none
- my_count
- my_map
- my_inject
- multiply_els (uses my inject to multiple a number array and return one result)

We used yield and procs on this project to make it work.

## Files to add:

* .gitignore
* .github/workflows/linters.yml
* .github/workflows/tests.yml
* enumerable.rb
* README.md
* MIT.md

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve
  - [x] [MANDATORY] #my_each when a block is given when self is an array returns the array itself after calling the given block once for each element in self.
    - when array is self and block is given. `[1,2,3,4].my_each(proc { |num| num % 2 = 0 })` 
       - Expected: `[1,2,3,4]` 
       - Got: `nil`
    - when range is self and block is given. `Range.new(5, 50).my_each(proc { |num| num % 2 = 0 })` 
       - Expected: `5..50` 
       - Got: `nil`
  - [x] [MANDATORY] #my_each_with_index when a block is given when self is an array returns the array itself after calling the given block once for each element in self.
     - when array is self and block is given. `[1,2,3,4].my_each(proc { |num| num % 2 = 0 })` 
       - Expected: `[1,2,3,4]` 
       - Got: `nil`
    - when range is self and block is given. `Range.new(5, 50).my_each(proc { |num| num % 2 = 0 })` 
       - Expected: `5..50` 
       - Got: `nil`
  - [x] [MANDATORY] #my_all? when no block or argument is given returns true when none of the collection members are false or nil.
    - when array is self and no block given ` [1, true, 'hi', []].my_all?`
      - Expected: `true`
      - Got: `false`
  - [x] [MANDATORY] #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer or class::Numeric. In this case, your function is throwing an error.
  - [x] [MANDATORY] #my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex. In this case, your function is throwing an error.
  - [x] [MANDATORY] #my_all? when a Regex is passed as an argument returns false if any of the collection does not match the Regex. In this case, your function is throwing an error.
  - [x] [MANDATORY] #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern. In this case, your function is throwing an error.
  - [x] [MANDATORY] #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern. In this case, your function is throwing an error.
  - [x] [MANDATORY] #my_any? when no block or argument is given returns true if at least one of the collection is not false or nil.
     - when an array is self and no block is given `[nil, false, true, []].my_any?`
       - Expected: `true`
       - Got: `false`
  - [x] [MANDATORY] #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class: Numeric, Integer, etc. In this case, your function is throwing an error.
  - [x] [MANDATORY] #my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex. In this case, your function is throwing an error.
  - [x] [MANDATORY] #my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex. In this case, your function is throwing an error.
  - [x] [MANDATORY] #my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern. In this case, your function is throwing an error.
  - [x] [MANDATORY] #my_any? when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern In this case your function is throwing an error.
  - [x] [MANDATORY] #my_none? when no block or argument is given returns true only if none of the collection members is true.
    - when an array is self and no block is given `[nil, false, nil, false].my_none?`
      - Expected: `true`
      - Got: `false`
  - [x] [MANDATORY] #my_none? when a class is passed as an argument returns true if none of the collection is a member of such class: Numeric, Integer, etc. In this case, your function is throwing an error.
     
  - [x] [OPTIONAL] It would be better to rename your file from enumerable.rb` to `enumerables.rb` so that it will be easier and faster for other TSEs to run and test your functions. 
    
         


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻✍️

Hello team, great work with the changes, I commend your energy and how you are keeping your code clean.

## To Improve [MANDATORY]
There are only a few test cases that are failing, kindly fix them so that we can get your project approved. I have also provided you with test cases.

- [x] `#my_select`

```ruby
let(:array) { Array.new(10) { rand(0...100)} }

it 'returns an enumerator if no block is given' do
    expect(array.my_select).to be_an(Enumerator)
end
```

- [x] `#my_count`
```ruby
it 'returns the number of items in enum through enumeration::range' do
    expect(Range.new(5, 50).my_count).to eq range.count
end
```


`#multiply_els`
```ruby
it 'accepts an array as an argument and multiplies all the elements of the array together using #my_inject' do
    result = multiply_els [2, 4, 5]
    expect(result).to eq 40
end
```

## Nice to have (OPTIONAL)
- [x] [Grammarly](https://www.grammarly.com) helps your write better with fewer errors, they have Google Chrome and Safari extensions. You can use this tool to better your grammar in your README, PR description, and overall.

Keep up the energy, and happy coding.

> ### You can find me on slack 👉 [CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance or clarification. I'm always available and will be glad to help.

**Comment by carlos-osorio-developer** [comment]
> 
> `#multiply_els`
> 
> ```ruby
> it 'accepts an array as an argument and multiplies all the elements of the array together using #my_inject' do
>     result = multiply_els [2, 4, 5]
>     expect(result).to eq 40
> end
> ```
> 

I believe this is a problem of syntax, you have to call the method in this way:

 ```ruby
> result = [2, 4, 5].multiply_els
> ```

**Comment by cyonii** [comment]
If I remember clearly the `multiply_els` method is not a method of the `Enumerable` module. Please verify this in your project's requirements.

I think it's an independent method, and therefore should be called like this 
```ruby
> multiply_els [1, 2, 5]

```

**Comment by carlos-osorio-developer** [comment]
> If I remember clearly the `multiply_els` method is not a method of the `Enumerable` module. Please verify this in your project's requirements.
> 
> I think it's an independent method, and therefore should be called like this
> 
> ```
> > multiply_els [1, 2, 5]
> ```

Thank you, I understand now.

But maybe you're missing the ( )? Like this:

 ```
 multiply_els([1, 2, 5])
 ```

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

### Congratulations @carlos-osorio-developer  and @JAAR91 on completing your project.

All your methods are running just as expect and has pass all tests, bravo! 👍 

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next project.


### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by cyonii** [comment]
Hey @carlos-osorio-developer, when you call or define a method in ruby you are allowed to omit the parenthesis in certain situations.

For learning purposes you can read this short article on [Arguments and parentheses](http://ruby-for-beginners.rubymonstas.org/bonus/parentheses.html).


```ruby
# These are the same
multiply_els([1, 2, 5]) == multiply_els [1, 2, 5]
```

**Pull request merged**
